name: CustomEnderEyes
version: "${project.version}"
main: me.wholesome_seal.custom_ender_eyes.Main
api-version: 1.19
authors: [wholesome_seal]

commands:
  endereye:
    description: General management command for the plugin
    permission: customendereyes.endereye

permissions:
  customendereyes.endereye:
    description: Permission to run all /endereye subcommands. Admin commmand
  customendereyes.*:
    description: Wildcard permission for all commands
    children:
      customendereyes.endereye: true
